name: conditional to trigger based on status

on: push

jobs:
 job_1:
    runs-on: ubuntu-latest
    steps:
    - name: name
      run: echo "anuhya"

 job_2:
    needs: job_1
    if: success()
    runs-on: ubuntu-latest
    steps:
    - name: status
      run: echo "success"

 job_3:
    needs: job_1
    if: failure()
    runs-on: ubuntu-latest
    steps:
    - name: status
      run: echo "failure"


